# Generated by Django 2.2.2 on 2019-12-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191203_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precise_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.preciseCategory'),
        ),
    ]
