# Generated by Django 2.2.2 on 2019-12-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191203_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precise_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.preciseCategory'),
        ),
    ]
