# Generated by Django 2.2.2 on 2019-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191203_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precise_category',
        ),
        migrations.AddField(
            model_name='product',
            name='precise_category',
            field=models.ManyToManyField(to='products.preciseCategory'),
        ),
    ]
