# Generated by Django 2.2.2 on 2019-12-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191203_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_posted']},
        ),
    ]
