# Generated by Django 2.2.2 on 2019-12-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191210_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precise_category',
        ),
        migrations.AddField(
            model_name='product',
            name='precise_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.preciseCategory'),
        ),
    ]
