# Generated by Django 2.2.2 on 2019-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191210_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='common_category',
        ),
        migrations.AddField(
            model_name='precisecategory',
            name='common_category',
            field=models.CharField(choices=[('WLB', 'work life balance'), ('ALP', 'activity lift people')], default='WLB', max_length=3),
        ),
    ]
