# Generated by Django 2.2.2 on 2019-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20191212_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='common_category',
            field=models.CharField(choices=[('WLB', 'work life balance'), ('ALP', 'activity lift people')], default='WLB', max_length=3),
        ),
    ]
